twitter-to-kafka-service:
  twitter-keywords:
    - PatriaYVida
    - EnCubaHayUnaDictadura 
    - 15NovCuba
    - Nos fuimos a la calle 
    - LibertadParaCuba
  welcome-message: Hello microservices!
enable-mock-tweets: false
mock-min-tweet-length: 5
mock-max-tweet-length: 15
mock-sleep-ms: 10000
